## Install a repository
- name: dnf-repos - Get GPG key
  ansible.builtin.get_url: 
    url: "{{ dnf_repos_repo_to_install.gpg_key_url }}"
    dest: /tmp/dnf-repos-tmp-{{ dnf_repos_repo_to_install.name }}.gpg
    use_proxy: "{{ dnf_repos_repo_to_install.proxy | bool }}"
    validate_certs: "{{ dnf_repos_repo_to_install.validate_certs | bool }}"
  environment:
    https_proxy: "{{ dnf_repos_repo_to_install.proxy | default(omit) }}"

## Install the repository
- name: dnf-repos - Store GPG key
  ansible.builtin.shell:
    cmd: install -m 644 /tmp/dnf-repos-tmp-{{ dnf_repos_repo_to_install.name }}.gpg /etc/pki/rpm-gpg/
    removes: /tmp/dnf-repos-tmp-{{ dnf_repos_repo_to_install.name }}.gpg

- name: dnf-repos - Install GPG key
  ansible.builtin.shell:
    cmd: rpm --import /etc/pki/rpm-gpg/dnf-repos-tmp-{{ dnf_repos_repo_to_install.name }}.gpg

## Cleanup
- name: dnf-repos - Delete GPG key
  ansible.builtin.file: 
    path: /tmp/dnf-repos-tmp-{{ dnf_repos_repo_to_install.name }}.gpg
    state: absent
