### Set vars
- name: dnf_repos - Set info
  ansible.builtin.set_fact:
    dnf_repos_repo_to_install: >
      {{
        dnf_repos_settings |
        selectattr('name', 'equalto', item) |
        first
      }}

- name: dnf-repos - Install
  when: dnf_repos_repo_to_install | length >= 1
  block:
  - name: dnf-repos - Import a repo setting - init
    ansible.builtin.set_fact:
      dnf_repos_append_repo_content: >
        {{
          {} |
          combine({"proxy": dnf_repos_repo_to_install.proxy | default(null)}) |
          combine(dnf_repos_repo_to_install.override | default({}))
        }}

  ### Check installed
  - name: dnf-repos - Check repos are installed
    ansible.builtin.stat:
      path: "{{ dnf_repos_repofile }}"
    register: dnf_repos_repofile_stat
    with_items: "{{ dnf_repos_repo_to_install.repofiles }}"
    loop_control:
      loop_var: dnf_repos_repofile

  - name: dnf-repos - Is installed
    ansible.builtin.set_fact:
      dnf_repos_repofile_installed: >
        {{ dnf_repos_repofile_stat.results |
          map(attribute='stat.exists') is all }}

  ### install
  - name: dnf-repos - Install GPG keys
    when: not ansible_check_mode and not dnf_repos_repofile_installed
    ansible.builtin.include_tasks: install_subtasks/install_gpg.yml

  - name: dnf-repos - Install repofile
    when: not ansible_check_mode and not dnf_repos_repofile_installed
    ansible.builtin.include_tasks: install_subtasks/install_rpm.yml

  ### edit repofiles
  - name: dnf-repos - Edit repofile
    with_items: "{{ dnf_repos_repo_to_install.repofiles }}"
    loop_control:
      loop_var: dnf_repos_edit_repo
    ansible.builtin.include_tasks: install_subtasks/modify.yml
